const cfg=window.RECIPE_APP_CONFIG||{};
const configured=cfg.supabaseUrl && !cfg.supabaseUrl.includes('YOUR_') && cfg.supabaseAnonKey && !cfg.supabaseAnonKey.includes('YOUR_');
const db=configured?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let categories=[],recipes=[],activeCategory='all',currentRecipe=null;
const LOGIN_USER='Tanrikulu';
const LOGIN_PASS='1943';
const $=id=>document.getElementById(id);
const icons={Soup:'🥣',Salad:'🥗',Beef:'🥩',Chicken:'🍗',Fish:'🐟',Shrimp:'🦐',Vegetable:'🥬',Breakfast:'🍳',Rice:'🍚',Dessert:'🍰'};
const fallbackCategories=['Soup','Salad','Beef','Chicken','Fish','Shrimp','Vegetable','Breakfast','Rice'];

async function init(){bind(); if(sessionStorage.getItem('tanrikulu-recipes-login')!=='yes'){showLogin();return;} hideLogin(); await initAfterLogin();}

function showLogin(){ $('loginScreen').classList.remove('hidden'); document.querySelector('.app-shell').classList.add('locked'); setTimeout(()=>$('loginUsername').focus(),50); }
function hideLogin(){ $('loginScreen').classList.add('hidden'); document.querySelector('.app-shell').classList.remove('locked'); }
function login(e){ e.preventDefault(); const ok=$('loginUsername').value.trim()===LOGIN_USER && $('loginPassword').value===LOGIN_PASS; if(!ok){$('loginError').classList.remove('hidden');$('loginPassword').value='';return;} sessionStorage.setItem('tanrikulu-recipes-login','yes'); $('loginError').classList.add('hidden'); hideLogin(); initAfterLogin(); }
function logout(){ sessionStorage.removeItem('tanrikulu-recipes-login'); location.reload(); }
async function initAfterLogin(){ if(!configured){categories=fallbackCategories.map((name,i)=>({id:`local-${i}`,name,sort_order:i})); recipes=sampleRecipes(); setStatus(false,'Demo mode — connect Supabase to share'); render();return;} try{await loadData();setStatus(true,'Family database connected');}catch(e){console.error(e);setStatus(false,'Could not connect');toast('Database connection failed');}}

async function loadData(){const [c,r]=await Promise.all([db.from('categories').select('*').order('sort_order'),db.from('recipes').select('*').order('recipe_number')]);if(c.error)throw c.error;if(r.error)throw r.error;categories=c.data;recipes=r.data;render();}
function bind(){ $('loginForm').onsubmit=login; $('logoutBtn').onclick=logout; $('newRecipeBtn').onclick=()=>openRecipeModal();$('addCategoryBtn').onclick=()=>$('categoryDialog').showModal();$('settingsBtn').onclick=()=>$('settingsDialog').showModal();$('randomBtn').onclick=randomRecipe;$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('searchInput').oninput=renderRecipes;$('recipeForm').onsubmit=saveRecipe;$('categoryForm').onsubmit=saveCategory;$('deleteRecipeBtn').onclick=deleteRecipe;$('editRecipeBtn').onclick=()=>{ $('viewDialog').close();openRecipeModal(currentRecipe);};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());}
function render(){renderCategories();renderRecipeSelect();renderRecipes();}
function renderCategories(){const list=$('categoryList');const all=`<div class="category-item ${activeCategory==='all'?'active':''}" data-id="all"><span>⌂</span><span>All recipes</span><span class="count">${recipes.length}</span></div>`;list.innerHTML=all+categories.map(c=>`<div class="category-item ${activeCategory===String(c.id)?'active':''}" data-id="${c.id}"><span>${icons[c.name]||'•'}</span><span>${esc(c.name)}</span><span class="count">${recipes.filter(r=>String(r.category_id)===String(c.id)).length}</span></div>`).join('');list.querySelectorAll('.category-item').forEach(el=>el.onclick=()=>{activeCategory=el.dataset.id;$('sidebar').classList.remove('open');render();});}
function renderRecipeSelect(){ $('recipeCategory').innerHTML=categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');}
function renderRecipes(){const q=$('searchInput').value.toLowerCase().trim();let shown=recipes.filter(r=>(activeCategory==='all'||String(r.category_id)===activeCategory)&&(!q||[r.name,r.ingredients,r.notes].join(' ').toLowerCase().includes(q)));const cat=categories.find(c=>String(c.id)===activeCategory);$('pageTitle').textContent=cat?cat.name:'All Recipes';$('pageSubtitle').textContent=cat?`Browse the family’s ${cat.name.toLowerCase()} recipes.`:'A shared collection of family favourites.';$('recipeCount').textContent=shown.length;$('recipeGrid').innerHTML=shown.map(r=>{const c=categories.find(x=>String(x.id)===String(r.category_id));return `<article class="recipe-card" data-id="${r.id}"><div class="card-top"><span class="number">#${String(r.recipe_number||0).padStart(3,'0')}</span><span class="tag">${esc(c?.name||'Recipe')}</span></div><h3>${esc(r.name)}</h3><div class="card-meta">${r.prep_time?`<span>Prep ${esc(r.prep_time)}</span>`:''}${r.cook_time?`<span>Cook ${esc(r.cook_time)}</span>`:''}${r.servings?`<span>Serves ${esc(r.servings)}</span>`:''}</div></article>`}).join('');$('emptyState').classList.toggle('hidden',shown.length>0);document.querySelectorAll('.recipe-card').forEach(el=>el.onclick=()=>viewRecipe(recipes.find(r=>String(r.id)===el.dataset.id)));}
function openRecipeModal(r=null){currentRecipe=r;$('recipeModalTitle').textContent=r?'Edit recipe':'Add recipe';$('recipeId').value=r?.id||'';$('recipeName').value=r?.name||'';$('recipeCategory').value=r?.category_id||categories[0]?.id||'';$('recipeServings').value=r?.servings||'';$('recipePrep').value=r?.prep_time||'';$('recipeCook').value=r?.cook_time||'';$('recipeIngredients').value=r?.ingredients||'';$('recipeMethod').value=r?.method||'';$('recipeNotes').value=r?.notes||'';$('deleteRecipeBtn').classList.toggle('hidden',!r);$('recipeDialog').showModal();}
async function saveRecipe(e){e.preventDefault();const id=$('recipeId').value;const payload={name:$('recipeName').value.trim(),category_id:$('recipeCategory').value,servings:$('recipeServings').value.trim(),prep_time:$('recipePrep').value.trim(),cook_time:$('recipeCook').value.trim(),ingredients:$('recipeIngredients').value.trim(),method:$('recipeMethod').value.trim(),notes:$('recipeNotes').value.trim()};if(!configured){if(id){const i=recipes.findIndex(r=>String(r.id)===id);recipes[i]={...recipes[i],...payload};}else recipes.push({...payload,id:'demo-'+Date.now(),recipe_number:nextNumber()});$('recipeDialog').close();render();toast('Saved in demo mode');return;}let res;if(id)res=await db.from('recipes').update(payload).eq('id',id);else res=await db.from('recipes').insert({...payload,recipe_number:nextNumber()});if(res.error)return toast(res.error.message);$('recipeDialog').close();await loadData();toast('Recipe saved');}
async function deleteRecipe(){if(!currentRecipe||!confirm(`Delete “${currentRecipe.name}”?`))return;if(configured){const {error}=await db.from('recipes').delete().eq('id',currentRecipe.id);if(error)return toast(error.message);}else recipes=recipes.filter(r=>r.id!==currentRecipe.id);$('recipeDialog').close();render();toast('Recipe deleted');}
async function saveCategory(e){e.preventDefault();const name=$('categoryName').value.trim();if(!name)return;if(configured){const {error}=await db.from('categories').insert({name,sort_order:categories.length});if(error)return toast(error.message);await loadData();}else{categories.push({id:'local-'+Date.now(),name,sort_order:categories.length});render();}$('categoryName').value='';$('categoryDialog').close();toast('Category added');}
function viewRecipe(r){currentRecipe=r;const c=categories.find(x=>String(x.id)===String(r.category_id));$('viewCategory').textContent=c?.name||'RECIPE';$('viewName').textContent=r.name;$('viewNumber').textContent='#'+String(r.recipe_number||0).padStart(3,'0');$('viewMeta').innerHTML=[r.prep_time&&`Prep ${r.prep_time}`,r.cook_time&&`Cook ${r.cook_time}`,r.servings&&`Serves ${r.servings}`].filter(Boolean).map(x=>`<span class="meta-chip">${esc(x)}</span>`).join('');$('viewIngredients').innerHTML=lines(r.ingredients).map(x=>`<li>${esc(x)}</li>`).join('');$('viewMethod').innerHTML=lines(r.method).map(x=>`<li>${esc(x)}</li>`).join('');$('viewNotes').textContent=r.notes||'';$('viewNotesWrap').classList.toggle('hidden',!r.notes);$('viewDialog').showModal();}
function randomRecipe(){let pool=recipes.filter(r=>activeCategory==='all'||String(r.category_id)===activeCategory);if(pool.length)viewRecipe(pool[Math.floor(Math.random()*pool.length)]);else toast('Add a recipe first');}
function nextNumber(){return Math.max(0,...recipes.map(r=>Number(r.recipe_number)||0))+1}function lines(s){return (s||'').split('\n').map(x=>x.trim()).filter(Boolean)}function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}function setStatus(ok,text){$('syncStatus').textContent=text;$('connectionTitle').textContent=ok?'Connected':'Not connected';$('connectionDetail').textContent=text;$('connectionDot').style.background=ok?'#4f8c67':'#c98d31'}
function sampleRecipes(){return [{id:'demo1',recipe_number:1,name:'Lemon Herb Chicken',category_id:'local-3',servings:'4',prep_time:'15 min',cook_time:'35 min',ingredients:'600 g chicken thighs\n2 tbsp olive oil\n1 lemon\n2 garlic cloves\nFresh thyme\nSalt and pepper',method:'Heat oven to 200°C.\nMix olive oil, lemon, garlic and thyme.\nCoat chicken and season well.\nRoast until golden and cooked through.',notes:'Excellent with roasted potatoes or a green salad.'},{id:'demo2',recipe_number:2,name:'Roasted Tomato Soup',category_id:'local-0',servings:'4',prep_time:'10 min',cook_time:'40 min',ingredients:'800 g tomatoes\n1 onion\n4 garlic cloves\nOlive oil\n500 ml vegetable stock\nFresh basil',method:'Roast tomatoes, onion and garlic until caramelised.\nTransfer to a pot with stock.\nSimmer for 10 minutes.\nBlend until smooth and finish with basil.',notes:''},{id:'demo3',recipe_number:3,name:'Mediterranean Shrimp',category_id:'local-5',servings:'3',prep_time:'10 min',cook_time:'12 min',ingredients:'500 g shrimp\nCherry tomatoes\nGarlic\nOlive oil\nParsley\nLemon',method:'Sauté garlic gently in olive oil.\nAdd shrimp and tomatoes.\nCook until shrimp are just pink.\nFinish with lemon and parsley.',notes:'Do not overcook the shrimp.'}];}
init();
