-- Run this once in Supabase > SQL Editor.
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  recipe_number integer not null unique,
  name text not null,
  contributor_name text default '',
  category_id bigint references public.categories(id) on delete set null,
  servings text,
  prep_time text,
  cook_time text,
  ingredients text not null,
  method text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.categories(name,sort_order) values
('Soup',1),('Salad',2),('Beef',3),('Chicken',4),('Fish',5),('Shrimp',6),('Vegetable',7),('Breakfast',8),('Rice',9)
on conflict(name) do nothing;

alter table public.categories enable row level security;
alter table public.recipes enable row level security;

-- Simple family version: anyone who has the site URL can read/write.
-- For stronger privacy, add Supabase Auth later and replace these policies.
create policy "public categories read" on public.categories for select using (true);
create policy "public categories insert" on public.categories for insert with check (true);
create policy "public recipes read" on public.recipes for select using (true);
create policy "public recipes insert" on public.recipes for insert with check (true);
create policy "public recipes update" on public.recipes for update using (true) with check (true);
create policy "public recipes delete" on public.recipes for delete using (true);
