-- TANRIKULU RECIPES V2 UPGRADE
alter table public.recipes add column if not exists photo_url text default '';
alter table public.recipes add column if not exists total_time text default '';
alter table public.recipes add column if not exists source_url text default '';

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  family_name text not null,
  created_at timestamptz default now(),
  unique(recipe_id, family_name)
);
alter table public.favorites enable row level security;
drop policy if exists "Family can read favorites" on public.favorites;
drop policy if exists "Family can add favorites" on public.favorites;
drop policy if exists "Family can delete favorites" on public.favorites;
create policy "Family can read favorites" on public.favorites for select to anon using (true);
create policy "Family can add favorites" on public.favorites for insert to anon with check (true);
create policy "Family can delete favorites" on public.favorites for delete to anon using (true);

-- Storage bucket for recipe photos
insert into storage.buckets (id,name,public) values ('recipe-photos','recipe-photos',true)
on conflict (id) do update set public=true;
drop policy if exists "Family can view recipe photos" on storage.objects;
drop policy if exists "Family can upload recipe photos" on storage.objects;
drop policy if exists "Family can update recipe photos" on storage.objects;
drop policy if exists "Family can delete recipe photos" on storage.objects;
create policy "Family can view recipe photos" on storage.objects for select to anon using (bucket_id='recipe-photos');
create policy "Family can upload recipe photos" on storage.objects for insert to anon with check (bucket_id='recipe-photos');
create policy "Family can update recipe photos" on storage.objects for update to anon using (bucket_id='recipe-photos') with check (bucket_id='recipe-photos');
create policy "Family can delete recipe photos" on storage.objects for delete to anon using (bucket_id='recipe-photos');

-- Permanent numbers: sequence is safer than calculating max+1 in the browser.
create sequence if not exists public.recipe_number_seq;
select setval('public.recipe_number_seq', greatest(coalesce((select max(recipe_number) from public.recipes),0),1));
alter table public.recipes alter column recipe_number set default nextval('public.recipe_number_seq');
